services:
  backend:
    image: prescripto-backend
    env_file:
      - ./backend/.env
    ports:
      - "127.0.0.1:4000:4000"

  frontend:
    image: prescripto-frontend
    ports:
      - "127.0.0.1:5173:4173"

  admin:
    image: prescripto-admin
    ports:
      - "127.0.0.1:5174:4173"
