name: Prescripto CI/CD

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Install admin dependencies
        working-directory: admin
        run: npm ci

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Lint frontend
        working-directory: frontend
        run: npm run lint

      - name: Lint admin
        working-directory: admin
        run: npm run lint

      - name: Lint backend
        working-directory: backend
        run: npm run lint

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Build admin
        working-directory: admin
        run: npm run build

      - name: Build backend
        working-directory: backend
        run: npm run build
